// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ginweb02/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/open/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/open/authorization",
				Handler: authorizationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: edituserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/open/verify",
				Handler: verifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/open/hello",
				Handler: helloWordHandler(serverCtx),
			},
		},
	)
}
